<a href="https://colab.research.google.com/github/hwankang/hoggorm/blob/master/11_(sun)_12_9_15_pm_PLS_comp_20.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget https://github.com/olivertomic/hoggorm
!pip install hoggorm

--2022-12-11 11:59:26--  https://github.com/olivertomic/hoggorm
Resolving github.com (github.com)... 140.82.112.4
Connecting to github.com (github.com)|140.82.112.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘hoggorm’

hoggorm                 [  <=>               ] 228.20K   940KB/s    in 0.2s

2022-12-11 11:59:27 (940 KB/s) - ‘hoggorm’ saved [233678]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting hoggorm
  Downloading hoggorm-0.13.3-py2.py3-none-any.whl (47 kB)
     |████████████████████████████████| 47 kB 1.4 MB/s
Requirement already satisfied: numpy>=1.9 in /usr/local/lib/python3.8/dist-packages (from hoggorm) (1.21.6)
Installing collected packages: hoggorm
Successfully installed hoggorm-0.13.3

In [2]:
!pip install hoggormplot

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting hoggormplot
  Downloading hoggormplot-0.13.2-py2.py3-none-any.whl (18 kB)
Requirement already satisfied: numpy>=1.9 in /usr/local/lib/python3.8/dist-packages (from hoggormplot) (1.21.6)
Installing collected packages: hoggormplot
Successfully installed hoggormplot-0.13.2

In [3]:
import hoggorm as ho
import hoggormplot as hop
import pandas as pd
import numpy as np

In [4]:
from google.colab import drive
drive.mount('/content/drive')
#filename='/content/drive/MyDrive/machine_learning/123_Raman_DATA_csv.csv'
filename='/content/drive/MyDrive/machine_learning/B_NIR_DATA_csv.csv'
import pandas as pd
X2_df = pd.read_csv(filename,header=0,encoding="unicode-escape")
X2_df

Mounted at /content/drive

,Unnamed: 0,¸ðµ¨ Æ÷ÇÔ,Y_B,899.9280058,900.2520706,900.5763689,900.9009009,901.2256669,901.5506671,901.8759019,...,2477.700694,2480.15873,2482.621648,2485.089463,2487.562189,2490.039841,2492.522433,2495.00998,2497.502498,2500
0,1,True,2.0,0.276093,0.279368,0.282974,0.283645,0.283141,0.282718,0.281553,...,2.949425,2.949937,2.940435,2.930193,2.927044,2.926591,2.917971,2.911627,2.911584,2.909855
1,2,True,1.8,0.199544,0.202455,0.206198,0.207755,0.208028,0.207398,0.205435,...,2.981332,2.984826,2.975499,2.964666,2.964128,2.967567,2.960830,2.954538,2.956946,2.955335
2,3,True,6.7,0.306803,0.309845,0.313508,0.314680,0.314671,0.314172,0.312433,...,2.991938,2.992541,2.984488,2.976776,2.975918,2.973828,2.963011,2.955492,2.954702,2.949301
3,4,True,6.2,0.286879,0.290392,0.294110,0.294774,0.294035,0.293060,0.291292,...,2.991402,2.990624,2.980183,2.970664,2.967151,2.961850,2.948892,2.939125,2.938542,2.934796
4,5,False,5.1,0.253218,0.256407,0.260161,0.261418,0.261547,0.261116,0.259408,...,3.004459,3.005398,3.000151,2.995331,2.997660,2.999729,2.992129,2.987290,2.988690,2.987576
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
619,620,True,8.6,0.231522,0.230534,0.231280,0.231104,0.230198,0.229698,0.229015,...,2.925508,2.927053,2.920447,2.915572,2.920224,2.922330,2.909775,2.897480,2.897737,2.897391
620,621,True,10.8,0.227531,0.226628,0.227406,0.227385,0.226585,0.225993,0.225327,...,2.945441,2.943505,2.933849,2.929372,2.934153,2.933573,2.921115,2.910637,2.914499,2.916288
621,622,True,12.2,0.224536,0.223379,0.224203,0.224431,0.223999,0.223736,0.222991,...,2.966221,2.969063,2.961253,2.952713,2.949854,2.944465,2.929207,2.920399,2.922437,2.923226
622,623,True,13.4,0.226519,0.225667,0.226440,0.226193,0.225218,0.224726,0.224143,...,2.936783,2.939133,2.927408,2.915374,2.913538,2.912847,2.901005,2.891991,2.894289,2.893951
623,624,True,15.8,0.233873,0.232724,0.233435,0.233191,0.232077,0.231309,0.230551,...,2.936938,2.938734,2.926707,2.915750,2.916544,2.919218,2.910248,2.899414,2.894074,2.890147

In [5]:
X3_df=X2_df.iloc[:,3:]
X3_df

,899.9280058,900.2520706,900.5763689,900.9009009,901.2256669,901.5506671,901.8759019,902.2013713,902.5270758,902.8530155,...,2477.700694,2480.15873,2482.621648,2485.089463,2487.562189,2490.039841,2492.522433,2495.00998,2497.502498,2500
0,0.276093,0.279368,0.282974,0.283645,0.283141,0.282718,0.281553,0.279137,0.279341,0.282978,...,2.949425,2.949937,2.940435,2.930193,2.927044,2.926591,2.917971,2.911627,2.911584,2.909855
1,0.199544,0.202455,0.206198,0.207755,0.208028,0.207398,0.205435,0.202679,0.203198,0.207066,...,2.981332,2.984826,2.975499,2.964666,2.964128,2.967567,2.960830,2.954538,2.956946,2.955335
2,0.306803,0.309845,0.313508,0.314680,0.314671,0.314172,0.312433,0.309447,0.309265,0.312464,...,2.991938,2.992541,2.984488,2.976776,2.975918,2.973828,2.963011,2.955492,2.954702,2.949301
3,0.286879,0.290392,0.294110,0.294774,0.294035,0.293060,0.291292,0.288594,0.288835,0.292392,...,2.991402,2.990624,2.980183,2.970664,2.967151,2.961850,2.948892,2.939125,2.938542,2.934796
4,0.253218,0.256407,0.260161,0.261418,0.261547,0.261116,0.259408,0.256675,0.257050,0.260721,...,3.004459,3.005398,3.000151,2.995331,2.997660,2.999729,2.992129,2.987290,2.988690,2.987576
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
619,0.231522,0.230534,0.231280,0.231104,0.230198,0.229698,0.229015,0.227028,0.224940,0.224793,...,2.925508,2.927053,2.920447,2.915572,2.920224,2.922330,2.909775,2.897480,2.897737,2.897391
620,0.227531,0.226628,0.227406,0.227385,0.226585,0.225993,0.225327,0.223806,0.222423,0.222653,...,2.945441,2.943505,2.933849,2.929372,2.934153,2.933573,2.921115,2.910637,2.914499,2.916288
621,0.224536,0.223379,0.224203,0.224431,0.223999,0.223736,0.222991,0.220813,0.218589,0.218392,...,2.966221,2.969063,2.961253,2.952713,2.949854,2.944465,2.929207,2.920399,2.922437,2.923226
622,0.226519,0.225667,0.226440,0.226193,0.225218,0.224726,0.224143,0.222250,0.220084,0.219543,...,2.936783,2.939133,2.927408,2.915374,2.913538,2.912847,2.901005,2.891991,2.894289,2.893951
623,0.233873,0.232724,0.233435,0.233191,0.232077,0.231309,0.230551,0.228832,0.227284,0.227713,...,2.936938,2.938734,2.926707,2.915750,2.916544,2.919218,2.910248,2.899414,2.894074,2.890147

In [6]:
X_df_train =X3_df.iloc[18:,:]
X_df=X_df_train
X_df

,899.9280058,900.2520706,900.5763689,900.9009009,901.2256669,901.5506671,901.8759019,902.2013713,902.5270758,902.8530155,...,2477.700694,2480.15873,2482.621648,2485.089463,2487.562189,2490.039841,2492.522433,2495.00998,2497.502498,2500
18,0.139177,0.141888,0.145298,0.146474,0.146784,0.146697,0.145243,0.142502,0.142762,0.146550,...,2.932393,2.929565,2.921381,2.914567,2.913292,2.910229,2.901862,2.898216,2.903621,2.903067
19,0.150201,0.153044,0.156581,0.157760,0.157673,0.156915,0.154994,0.152210,0.152600,0.156411,...,2.943797,2.944384,2.932363,2.922442,2.926306,2.927773,2.914076,2.900709,2.899962,2.897292
20,0.250733,0.253317,0.256558,0.257606,0.257595,0.257003,0.255303,0.252790,0.253315,0.256932,...,3.034629,3.033398,3.025594,3.021798,3.026779,3.030004,3.018231,3.010140,3.011915,3.012127
21,0.406021,0.409663,0.413927,0.415266,0.414759,0.413630,0.411848,0.409522,0.410283,0.414297,...,2.992735,2.993004,2.985957,2.978901,2.977395,2.974942,2.963776,2.956788,2.959520,2.959698
22,0.156773,0.159704,0.163289,0.164755,0.165101,0.164654,0.162993,0.160581,0.161232,0.164964,...,2.954054,2.967308,2.953726,2.948256,2.956160,2.954848,2.935037,2.921605,2.921331,2.916948
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
619,0.231522,0.230534,0.231280,0.231104,0.230198,0.229698,0.229015,0.227028,0.224940,0.224793,...,2.925508,2.927053,2.920447,2.915572,2.920224,2.922330,2.909775,2.897480,2.897737,2.897391
620,0.227531,0.226628,0.227406,0.227385,0.226585,0.225993,0.225327,0.223806,0.222423,0.222653,...,2.945441,2.943505,2.933849,2.929372,2.934153,2.933573,2.921115,2.910637,2.914499,2.916288
621,0.224536,0.223379,0.224203,0.224431,0.223999,0.223736,0.222991,0.220813,0.218589,0.218392,...,2.966221,2.969063,2.961253,2.952713,2.949854,2.944465,2.929207,2.920399,2.922437,2.923226
622,0.226519,0.225667,0.226440,0.226193,0.225218,0.224726,0.224143,0.222250,0.220084,0.219543,...,2.936783,2.939133,2.927408,2.915374,2.913538,2.912847,2.901005,2.891991,2.894289,2.893951
623,0.233873,0.232724,0.233435,0.233191,0.232077,0.231309,0.230551,0.228832,0.227284,0.227713,...,2.936938,2.938734,2.926707,2.915750,2.916544,2.919218,2.910248,2.899414,2.894074,2.890147

In [7]:
X_df_test =X3_df.iloc[0:18,:]
X_df_test

,899.9280058,900.2520706,900.5763689,900.9009009,901.2256669,901.5506671,901.8759019,902.2013713,902.5270758,902.8530155,...,2477.700694,2480.15873,2482.621648,2485.089463,2487.562189,2490.039841,2492.522433,2495.00998,2497.502498,2500
0,0.276093,0.279368,0.282974,0.283645,0.283141,0.282718,0.281553,0.279137,0.279341,0.282978,...,2.949425,2.949937,2.940435,2.930193,2.927044,2.926591,2.917971,2.911627,2.911584,2.909855
1,0.199544,0.202455,0.206198,0.207755,0.208028,0.207398,0.205435,0.202679,0.203198,0.207066,...,2.981332,2.984826,2.975499,2.964666,2.964128,2.967567,2.960830,2.954538,2.956946,2.955335
2,0.306803,0.309845,0.313508,0.314680,0.314671,0.314172,0.312433,0.309447,0.309265,0.312464,...,2.991938,2.992541,2.984488,2.976776,2.975918,2.973828,2.963011,2.955492,2.954702,2.949301
3,0.286879,0.290392,0.294110,0.294774,0.294035,0.293060,0.291292,0.288594,0.288835,0.292392,...,2.991402,2.990624,2.980183,2.970664,2.967151,2.961850,2.948892,2.939125,2.938542,2.934796
4,0.253218,0.256407,0.260161,0.261418,0.261547,0.261116,0.259408,0.256675,0.257050,0.260721,...,3.004459,3.005398,3.000151,2.995331,2.997660,2.999729,2.992129,2.987290,2.988690,2.987576
5,0.165341,0.168096,0.171707,0.173095,0.173221,0.172616,0.170830,0.168136,0.168463,0.172067,...,2.992120,2.991850,2.980991,2.972400,2.972670,2.972324,2.958664,2.948479,2.948137,2.944359
6,0.220883,0.223903,0.227404,0.228520,0.228443,0.227757,0.226051,0.223639,0.224288,0.228008,...,2.954999,2.959127,2.950034,2.941829,2.942999,2.944108,2.935344,2.925908,2.926498,2.927566
7,0.128466,0.131093,0.134434,0.135520,0.135453,0.134727,0.132757,0.129794,0.129877,0.133345,...,2.965950,2.964856,2.951359,2.940985,2.940009,2.939985,2.929271,2.922497,2.923163,2.921886
8,0.126331,0.129429,0.133110,0.134365,0.134569,0.134341,0.132864,0.130208,0.130523,0.134228,...,2.955796,2.957617,2.948017,2.939907,2.942179,2.943938,2.935434,2.924869,2.922034,2.920252
9,0.291173,0.294134,0.297736,0.298926,0.298955,0.298521,0.297009,0.294487,0.294844,0.298385,...,2.975130,2.975795,2.966461,2.961597,2.965299,2.965209,2.954790,2.945580,2.943033,2.938797
10,0.220247,0.223108,0.226791,0.228110,0.228130,0.227503,0.225673,0.222819,0.223060,0.226865,...,2.983917,2.985588,2.973288,2.966548,2.968611,2.966015,2.946620,2.933276,2.937377,2.939676
11,0.328231,0.331323,0.334716,0.335458,0.335420,0.335360,0.334137,0.331547,0.331787,0.335348,...,2.988838,2.990282,2.981027,2.974527,2.980125,2.988291,2.982260,2.970503,2.967734,2.965919
12,0.137633,0.141045,0.144793,0.145757,0.145570,0.145180,0.143793,0.141257,0.141577,0.145204,...,2.912618,2.911201,2.898590,2.887394,2.886869,2.887019,2.875892,2.863482,2.862177,2.858754
13,0.139231,0.142147,0.145743,0.146953,0.146887,0.146160,0.144310,0.141556,0.141772,0.145231,...,2.930897,2.929484,2.916850,2.906049,2.903512,2.901345,2.892460,2.886911,2.888303,2.885096
14,0.142883,0.146037,0.149645,0.150603,0.150553,0.150323,0.148906,0.146081,0.146080,0.149688,...,2.928713,2.929209,2.921265,2.911780,2.910932,2.907801,2.897550,2.888132,2.889102,2.890579
15,0.137030,0.140187,0.143767,0.144933,0.145065,0.144696,0.143124,0.140637,0.141329,0.145357,...,2.953141,2.952883,2.943807,2.937052,2.937185,2.936275,2.927236,2.916444,2.914460,2.911749
16,0.141540,0.144548,0.148296,0.149544,0.149392,0.148602,0.146731,0.143917,0.144086,0.147622,...,2.948055,2.948948,2.939812,2.932491,2.933737,2.934073,2.923589,2.914205,2.913873,2.910130
17,0.141872,0.144643,0.148012,0.149049,0.148993,0.148358,0.146462,0.143556,0.143779,0.147471,...,2.934504,2.933159,2.921653,2.910368,2.908329,2.906151,2.896466,2.887998,2.887455,2.886169

In [8]:
Y3_df=X2_df.iloc[:,2:3]
Y3_df

      Y_B
0     2.0
1     1.8
2     6.7
3     6.2
4     5.1
..    ...
619   8.6
620  10.8
621  12.2
622  13.4
623  15.8

[624 rows x 1 columns]

In [9]:
Y_df_target =Y3_df.iloc[18:,:]
Y_df=Y_df_target
Y_df

      Y_B
18    0.0
19    0.0
20    0.0
21    0.0
22    0.0
..    ...
619   8.6
620  10.8
621  12.2
622  13.4
623  15.8

[606 rows x 1 columns]

In [10]:
Y_df_ground =Y3_df.iloc[0:18,:]
Y_df_true= Y_df_ground
Y_df_true

     Y_B
0    2.0
1    1.8
2    6.7
3    6.2
4    5.1
5   13.7
6    0.0
7    0.0
8    0.0
9    0.0
10   0.0
11   0.0
12   2.2
13   2.4
14   4.0
15   7.8
16   9.4
17   8.2

In [12]:
# Get the values from the data frame
X = X_df.values
Y = Y_df.values

# Get the variable or columns names
X_varNames = list(X_df.columns)
Y_varNames = list(Y_df.columns)

# Get the object or row names
X_objNames = list(X_df.index)
Y_objNames = list(Y_df.index)

In [ ]:
model = ho.nipalsPLS2(arrX=X, Xstand=False, 
                      arrY=Y, Ystand=False,
                      cvType=["loo"], 
                      numComp=20)

loo

In [15]:
# Get validated predicted Y for a given number of components

# Predicted Y from validation using 18 components
Y_from_component_val = model.Y_predVal()[18]

# Predicted Y from calibration using 3 components stored in pandas data frame with row and columns names
Y_from_component_val_df = pd.DataFrame(model.Y_predVal()[18])
Y_from_component_val_df.index = Y_objNames
Y_from_component_val_df.columns = Y_varNames
Y_from_component_val_df

           Y_B
18    1.381217
19    3.180294
20    2.270657
21    6.829947
22   -1.555283
..         ...
619   8.726950
620   8.558869
621  11.739212
622  10.802197
623  19.167669

[606 rows x 1 columns]

In [16]:
new_X =X_df_test
# Now insert the new data into the existing model and compute scores for two components (numComp=2)
#pred_X_scores = model.X_scores_predict(new_X, numComp=2)
pred_X_scores = model.X_scores_predict(new_X, numComp=18)

# Same as above, but results stored in a pandas dataframe with row names and column names
pred_X_scores_df = pd.DataFrame(model.X_scores_predict(new_X, numComp=18))
pred_X_scores_df.columns = ['comp {0}'.format(x+1) for x in range(18)]
pred_X_scores_df.index = ['new object {0}'.format(x+1) for x in range(np.shape(new_X)[0])]
pred_X_scores_df

,comp 1,comp 2,comp 3,comp 4,comp 5,comp 6,comp 7,comp 8,comp 9,comp 10,comp 11,comp 12,comp 13,comp 14,comp 15,comp 16,comp 17,comp 18
new object 1,4.681544,2.081836,-0.462689,-0.106402,-0.334583,3.467190,0.350804,-0.167409,0.372609,0.633747,0.190683,-0.170120,-0.183458,-0.109643,0.181330,-0.175162,-0.063476,0.073642
new object 2,3.075278,0.959103,-0.232614,-0.099093,-0.309686,1.142094,0.112111,-0.211832,0.208804,0.382313,0.007148,-0.016301,-0.067551,-0.043147,0.044802,-0.055118,0.048096,0.037018
new object 3,5.128682,2.260371,-0.658607,-0.220128,-0.442180,4.253884,0.445462,-0.153210,0.426599,0.664273,0.327688,0.007064,-0.011296,-0.109549,0.118358,-0.076791,0.011533,-0.022083
new object 4,6.022001,2.566212,-0.586269,-0.032730,-0.538298,3.112081,0.306577,-0.272121,0.429122,0.545562,0.310798,0.177548,0.156745,-0.020723,0.121377,-0.040201,0.060823,0.014232
new object 5,2.788395,1.062184,-0.282510,0.067521,-0.065095,3.455049,0.102114,-0.328890,0.113171,0.539990,0.017363,-0.193737,0.080549,0.043710,0.217341,-0.085910,0.063190,0.055952
new object 6,-8.647837,-2.120171,-0.287867,0.237624,0.317618,2.385880,-0.729335,-0.293022,0.129567,0.106577,0.258228,0.183711,-0.238743,0.126641,0.083841,0.052126,-0.040591,-0.065508
new object 7,3.512541,1.366661,-0.229803,-0.137012,-0.344651,1.529898,0.163125,-0.199248,0.197625,0.306040,0.079032,-0.036031,-0.057482,-0.033430,0.097955,-0.045029,0.072182,0.017920
new object 8,1.002644,-0.079488,0.045390,-0.153165,-0.028626,-0.590604,-0.023047,-0.066697,0.085362,0.189037,-0.076352,-0.093448,-0.061145,-0.075067,-0.065810,-0.040451,-0.011550,-0.019763
new object 9,1.827036,0.144888,0.058043,-0.033415,-0.086301,-0.933813,-0.060575,-0.143339,0.053550,0.148012,-0.092532,-0.098417,-0.038081,-0.029464,-0.060719,-0.030734,-0.018081,0.006874
new object 10,5.193330,2.306545,-0.612626,-0.278158,-0.477695,3.625349,0.339662,-0.135470,0.439001,0.571008,0.261969,0.017793,-0.077309,-0.089218,0.139610,-0.064470,0.039867,0.023282
new object 11,-6.266927,-1.126809,-0.505885,0.055205,0.203196,3.939607,-0.412144,-0.235518,0.326249,0.222315,0.295088,0.117204,-0.280948,0.017186,0.195680,0.013365,-0.078463,0.019261
new object 12,4.649704,1.979878,-1.141950,-0.052595,-0.099598,5.721473,0.222909,-0.174348,0.387529,0.614844,0.314560,-0.076373,-0.135809,-0.067446,0.226788,-0.150131,-0.027659,-0.017377
new object 13,2.198782,0.604856,0.015032,-0.019150,0.017559,-0.571034,-0.027736,-0.096051,0.198564,0.254638,0.143164,-0.154631,-0.122547,-0.122901,-0.026441,-0.050984,-0.008967,-0.009502
new object 14,3.023837,0.759343,-0.017816,0.074581,-0.019455,-0.803235,0.038940,-0.180137,0.059682,-0.006761,0.202787,-0.103792,-0.041643,-0.105357,-0.050622,0.009420,0.035077,-0.001548
new object 15,3.025737,0.849940,0.072463,0.243715,0.268132,-0.336144,-0.020200,-0.240178,0.020279,-0.128945,0.282000,-0.189249,0.117510,-0.005080,-0.056021,-0.016595,0.056135,-0.037836
new object 16,2.186278,0.342350,0.001211,-0.062101,-0.211163,-0.845863,-0.003045,-0.071928,0.218211,0.346633,-0.016610,-0.032919,-0.029722,-0.050974,-0.003016,-0.024950,0.010821,-0.002025
new object 17,2.500355,0.457372,0.044029,-0.057727,-0.212503,-0.910603,-0.051833,-0.102643,0.190376,0.268689,0.022533,0.054758,0.043326,0.054089,0.042389,0.028818,0.042153,-0.010277
new object 18,2.382594,0.477417,0.059019,-0.041948,-0.216912,-0.907244,-0.055812,-0.064292,0.308035,0.439974,0.051721,0.031461,0.011875,0.037630,0.007064,-0.044343,-0.040117,-0.007383

In [17]:
# Predict Y from new X data
pred_Y = model.Y_predict(new_X, numComp=18)

# Predict Y from nex X data and store results in a pandas dataframe with row names and column names
pred_Y_df = pd.DataFrame(model.Y_predict(new_X, numComp=18))
pred_Y_df.columns = Y_varNames
pred_Y_df.index = ['new object {0}'.format(x+1) for x in range(np.shape(new_X)[0])]
pred_Y_df

                     Y_B
new object 1    5.123756
new object 2    4.299785
new object 3    9.946707
new object 4   13.521866
new object 5    7.974035
new object 6    3.576597
new object 7    5.599700
new object 8    0.028568
new object 9    0.255865
new object 10   9.582301
new object 11   5.918560
new object 12   8.132983
new object 13   1.473216
new object 14   2.534147
new object 15   4.452972
new object 16   3.644738
new object 17   7.084953
new object 18   5.839588

In [18]:
from sklearn.metrics import mean_squared_error, r2_score
mse= mean_squared_error(Y_df_true, pred_Y_df)
rmse=np.sqrt(mse)
r2=r2_score(Y_df_true, pred_Y_df)

In [19]:
print('MSE : {: 0.3f}, || RMSE : {: 0.3f}, || R2 : {: 0.3f}'.format(mse,rmse,r2))

MSE :  24.682, || RMSE :  4.968, || R2 : -0.593